### ISSUE TITLE
Integrate into SageMath

### ISSUE THREAD

**Issue by pfasante** [hadipourh/comeback#1]
If I understand correctly, integrating this solution into SageMath would require ESPRESSO being available in it, is that right?
Regarding that, I see that you have already asked on the SageMath google groups some time ago about how that'd work (see https://groups.google.com/g/sage-devel/c/fECjDlKAroU/m/y89rkByzBAAJ).

What other prerequisites would there be, to upstream your implementation to SageMath?

**Comment by pfasante** [comment]
Actually, in the paper you mention that you used ESPRESSO, but I cannot find any hint on this in the provided source code in this repository?

**Comment by hadipourh** [comment]
Hi Fredrick,

Thanks for your question. 

Regarding upstreaming our S-box tool to SageMath, yes, we only need the ESPRESSO being available in SageMath.
Concerning your second question, we have actually provided a dedicated repository for our S-box tool here:
https://github.com/hadipourh/sboxanalyzer

**Note that the repository of our S-box tool is empty now since I am currently extending the tool in terms of application and providing brief documentation for its usage. I try my best to upload the source codes by July 22, 2022, at the latest.** We have provided a Python (SageMath) interface to employ ESPRESSO for extracting and simplifying the MILP/SMT/SAT constraints for encoding the DDT/LAT of S-boxes. I am also extending the tool for encoding the division property and monomial prediction table of S-boxes as well. I will notify you soon after uploading the codes by the way.

The original source code of ESPRESSO comes from the [University of California, Berkeley](https://embedded.eecs.berkeley.edu/pubs/downloads/espresso/index.htm). However, this original version is written in old C and thus not compatible with new compilers. Fortunately, an updated version of ESPRESSO is rehosted [here](https://github.com/classabbyamp/espresso-logic) which is compatible with new compilers. I also used the updated version in my tool. Another good news is that this package is now available on the [Arch User Repository](https://aur.archlinux.org/packages/espresso-logic) which makes it easier to use for Arch-based Linux users.

I am interested to integrate this tool into the SageMath if possible. The first and actually the main challenge is integrating the ESPRESSO logic minimization tool into the SageMath. As far as I know, you have already contributed to cryptographic modules of SageMath and I appreciate it if you let me know your opinion concerning this aim.

**Comment by pfasante** [comment]
Alright, then this issue should be opened in the sboxanalyzer repository, I think. I'll close this one.

Regarding adding ESPRESSO to sage: lets see if we get an answer in the google groups thread. I have not yet worked on including new packages into sage.
